version: '3.8'

services:
  caching-proxy-redis:
    image: redis
    container_name: caching-proxy-redis
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
